### ISSUE TITLE
TODO before submission

### ISSUE THREAD

**Issue by DunklesArchipel** [theoechem/article_MAHE_2024_IL_pitfalls#1]
- [x] Add Link to ChemRxiv
- [x] turn folder/files in README into URLs
- [x] update repo name in installation instructions (see #4)
- [x] Add Readme for XPS data (see #4)
- [x] Add notebook to explore CVs with unitpackage (see #4)
- [x] Publish Zenodo
- [x] add Zenodo Tag
- [x] Fix database notebook (remove package versions, since they are included in the environment.yml) (see #4)
